### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by Ecalpal** [ELOESZHANG/MPCF--3d_object_detection#1]
Great job!

Do you have any plan to release the pre-print paper?

**Comment by ELOESZHANG** [comment]
I'm submitting to IEEE Transactions on Circuits and Systems for Video Technology (TCSVT). Sorry, I currently have no plans to release the paper.

**Comment by Ecalpal** [comment]
It's fine. 

Please let me know when your paper is accepted.
